/* 1.Realizar consultas para contestar las siguientes preguntas:*/

SELECT * FROM menu_items;

--Encontrar el número de artículos en el menú--

SELECT COUNT (*) AS NÚMERO_DE_ARTÍCULOS
	FROM MENU_ITEMS;

--¿Cuál es el artículo menos caro y el más caro en el menú?--
--MENOS CARO--
SELECT MIN (PRICE) AS PRECIO_MAS_BAJO
FROM MENU_ITEMS;

--MÁS CARO--
SELECT MAX (PRICE) AS PRECIO_MAS_ALTO
FROM MENU_ITEMS;

--¿Cuántos platos americanos hay en el menú?--
SELECT * FROM MENU_ITEMS
WHERE CATEGORY LIKE 'American';

--¿Cuál es el precio promedio de los platos?--
SELECT AVG (PRICE) AS PROMEDIO_DE_LOS_PLATOS 
	FROM MENU_ITEMS;

/* 2.- Realizar consultas para contestar las siguientes preguntas:*/
SELECT * FROM ORDER_DETAILS;
--¿Cuántos pedidos únicos se realizaron en total?
SELECT DISTINCT (ITEM_ID) FROM ORDER_DETAILS;
--¿Cuáles son los 5 pedidos que tuvieron el mayor número de artículos?

SELECT ORDER_ID, COUNT(ITEM_ID)
FROM ORDER_DETAILS
GROUP BY ORDER_ID
ORDER BY COUNT (ITEM_ID) DESC
LIMIT 5;

--¿Cuándo se realizó el primer pedido y el último pedido?
--PRIMER PEDIDO
SELECT MIN (ORDER_DATE) AS PRIMER_PEDIDO
FROM ORDER_DETAILS;

--SEGUNDO PEDIDO
SELECT MAX (ORDER_DATE) AS ULTIMO_PEDIDO
FROM ORDER_DETAILS;

--¿Cuántos pedidos se hicieron entre el '2023-01-01' y el '2023-01-05'?

SELECT * FROM ORDER_DETAILS
WHERE ORDER_DATE BETWEEN '2023-01-01'  AND '2023-01-05';

/*1.- Realizar un left join entre entre order_details y menu_items con el identificador
item_id(tabla order_details) y menu_item_id(tabla menu_items).*/

SELECT ORDER_DETAILS.ITEM_ID,
FROM ORDER_DETAILS
LEFT JOIN MENU_ITEMS
ON ORDER_DETAILS.ITEM_ID=MENU_ITEMS.MENU_ITEM_ID;

--CONSULTAS ADICIONALES

SELECT MENU_ITEM.CATEGORY,
	MENU_ITEM.ITEM_NAME,
	MENU_ITEM.PRICE,
	MENU_ITEM.MENU_ITEM_ID
	FROM MENU_ITEM
LEFT JOIN ORDER_DETAILS
ON MENU_ITEMS.MENU_ITEM_ID=ORDER_DETAILS.ITEM_ID;

-- CONCLUSIONES
-- LOS DATOS TIENEN UN PERIODO DE 3 MESES DE RECOLECCIÓN, POR LO QUE PUEDE QUE SEA BUENO RECOLECTAR MÁS INFORMACIÓN QUE APORTE DATOS.
-- EL PROMEDIO DE COSTO DE LOS ALIMENTOS ES ALREDEDOR DE $13, POR LO QUE, SE PODRÍA REALIZAR UNA HOMOGENIZACIÓN DE PRECIOS COMO ESTRATEGIA DE VENTA PARA TODOS LOS PRODUCTOS. 
-- SE PUEDEN CREAR COMBOS ENTRE LOS PRODUCTOS, POTENCIANDO LA VENTA DE AQUELLOS QUE POR SI SOLOS NO SE VENDEN BIEN. 
-- SE PUEDEN LANZAR DESCUENTOS POR NÚMEROS DE ARTÍCULOS COMPRADOS, TENIENDO UNA ESCALA ASCENDENTE CONFORME MÁS ARTÍCULOS SE CONSUMAN EN UNA MISMA ORDEN. 
-- EL NUMERO DE PEDIDOS POR DÍA ES ELEVADO, SE PODRÍAN ANALIZAR LAS HORAS EN LAS QUE LOS PEDIDOS SON MENORES Y LANZAR CAMPAÑAS PROMOCIONALES PARA INCENTIVAR LA VENTA. 

